# Generated by Django 5.0.7 on 2024-08-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleVenta',
            fields=[
                ('idDetalleVe', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('idDetalleVen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='tienda.detalleventa')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_login.usuarios')),
            ],
        ),
    ]
