# Generated by Django 5.0.7 on 2024-08-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=10),
        ),
    ]
