# Generated by Django 5.0.7 on 2024-08-27 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=50)),
                ('numero_transaccion', models.CharField(max_length=100, unique=True)),
                ('fecha_transaccion', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='idDetalleVe',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idDetalleVen',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_ventas',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(related_name='ventas', through='tienda.DetalleVenta', to='tienda.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='transferencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='tienda.transferencia'),
        ),
    ]
