# Generated by Django 5.0.7 on 2024-08-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
        ('inicio', '0002_rename_modelo_modelo_nombre_and_more'),
        ('tienda', '0005_transferencia_remove_detalleventa_iddetalleve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_equipo', models.CharField(max_length=100)),
                ('donador', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='inicio.empleado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='tienda.producto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='inicio.sucursal')),
            ],
        ),
        migrations.DeleteModel(
            name='donaciones',
        ),
    ]
