# Generated by Django 5.0.7 on 2024-08-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_login', '0001_initial'),
        ('tienda', '0005_transferencia_remove_detalleventa_iddetalleve_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roles',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
