# Generated by Django 5.0.7 on 2024-08-27 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_modelo_modelo_nombre_and_more'),
        ('soporteTecnico', '0001_initial'),
        ('tienda', '0005_transferencia_remove_detalleventa_iddetalleve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to='inicio.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('respuesta', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_reclamo', to='inicio.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='repaciones',
        ),
        migrations.DeleteModel(
            name='respuesta_reclamo',
        ),
        migrations.AddField(
            model_name='estado',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='tienda.producto'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha_equipo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='respuestareclamo',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='soporteTecnico.reclamo'),
        ),
    ]
